### ISSUE TITLE
Feature: Clickable keywords

### ISSUE THREAD

**Issue by MatthewBerglund** [MatthewBerglund/nytimes-article-searcher#15]
The user should be able to click on the keywords in the search results to submit a new search with the clicked keyword as the search query.

Things to consider:
- Should the applied filters and other options remain the same when this happens? What makes the most sense in terms of user expectations?

**Comment by MatthewBerglund** [comment]
Quick question @motine : what would you like to have happen when the user clicks one of the keywords/tags?

We could:

a. Clear all the filters and submit a brand new search with the clicked keyword as the main search query.
b. Submit a new search for the keyword with all filters kept the same.
c. Use the keyword to further filter the current search.

My personal feeling is that option **a** is probably what users expect to have happen.

**Comment by motine** [comment]
great preparation! thanks so much. a) sounds great.
