### ISSUE TITLE
Feature: Clickable author name

### ISSUE THREAD

**Issue by MatthewBerglund** [MatthewBerglund/nytimes-article-searcher#17]
The application should display the name of the article's author and provide the user with the ability to click the name and perform a search for all articles written by that author.

**Comment by MatthewBerglund** [comment]
Hey @motine,

We can add clickable author names, but there is no way to limit the search to the byline only (where the author's name appears). The API only provides the ability to search for the author name as if it were a general search term, so it will return not only results where the byline contains the correct author name, but also articles written by other authors (maybe because part of the author's name appears in the headline or the body of the article). 

But despite this, searching by author name generally works they way you would expect. So when the user clicks an author name, we can have the app submit a new search with the author name as the search query. How does this sound?

**Comment by motine** [comment]
I found this 
<img width="427" alt="image" src="https://user-images.githubusercontent.com/1439041/149722863-65b2cff3-ae99-40ac-8098-2b2fd99627bc.png">
on here https://developer.nytimes.com/docs/articlesearch-product/1/overview

Do you think this is relevant?

(aside: POs search the internet all the time and find stuff that may or may not fit the solution)

**Comment by MatthewBerglund** [comment]
Yeah, unfortunately it isn't relevant for what we want. For whatever reason, the `byline.person` key in the fetched JSON data, which contains the names of the authors, is not the same "person" that the `persons` or `persons.contains` filters look for. These filters actually look for names of persons among the article keywords: e.g. "Merkel, Angela", "Gates, Bill", etc. Searching for authors with these filters returns 0 results.

**Comment by motine** [comment]
alright. thanks for the research. let's close this issue then.
