### ISSUE TITLE
Issue: Color-coding interactive elements

### ISSUE THREAD

**Issue by MatthewBerglund** [MatthewBerglund/nytimes-article-searcher#21]
It isn't always clear when an element is clickable. We need a unambiguous color-code for interactive elements.

**Comment by MatthewBerglund** [comment]
@motine Here's a potential solution to the color problem: 

I think this makes it clearer that "Show filters" and the article headlines are clickable.

![chrome_3U60bx5Okx](https://user-images.githubusercontent.com/26901435/149914174-04dfaf27-83a5-4ddd-b370-d754125eb917.png)

**Comment by motine** [comment]
much better. maybe also hightlicht the calendar icons. also, I am not sure about the color of the search button color. we could treat it as a design choice. up to you.

**Comment by MatthewBerglund** [comment]
I'm open to changing colors as long as everything looks good together. What were you thinking for the button?

**Comment by motine** [comment]
maybe also blue? please make a decision. :)
thanks again for the changes. I think this is much more clear.
